### ISSUE TITLE
zerohub client should be part of std jumpscale

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/sandbox#4] opened 2018-04-29 06:20 UTC
why?

pip3 install -e 'git+https://github.com/zero-os/0-hub#egg=zerohub&subdirectory=client'

for all other components we wrap in jumpscale, so why should we not do this for our own components?
Or you wrap & then the pip3 should be done when installing js93
Or you have the client in js93 in the code repo itself

**Comment by ahussein** [comment] 2018-05-03 11:43
the hub client is only used to merge  the generated flist with a base ubuntu flist, so its not really part of the sandboxing process for js9.
We can for sure include it when creating the js9 sandbox as well.

**Comment by zaibon** [comment] 2018-05-03 12:56
This has nothing to do with your sandboxing process.
Problem is the zero-hub client code is out of jumpscale and this is wrong.
It should be included into jumspcale lib9 like any other client

**Comment by ahussein** [comment] 2018-05-07 09:10
I will move this to lib9 repository.

**Comment by ahussein** [comment] 2018-05-07 09:13
duplicate of https://github.com/Jumpscale/lib9/issues/249

**Closed** 2018-05-07 10:02 UTC
Labels: priority_critical
